<?php

/**
 * Contact - phpManufaktur
 *
 * This file was generated by the kitFramework
 */
 
$module_directory     = 'kit_framework_contact';
$module_name          = 'Contact';
$module_function      = 'tool';
$module_version       = '2.0.27';
$module_platform      = '2.8.x';
$module_author        = 'phpManufaktur';
$module_license       = 'MIT License';
$module_description   = 'Contact management for kitFramework';
$module_guid          = '{GUID}';
