<?php

/**
 * Event - phpManufaktur
 *
 * This file was generated by the kitFramework
 */
 
if ('á' != "\xc3\xa1") {
  // important: language files must be saved as UTF-8 (without BOM)
  trigger_error("The language file <b>".basename(__FILE__)."</b> is damaged, it must be saved <b>UTF-8</b> encoded!", E_USER_ERROR);
}

// description of the module, used by the Admin-Tools and the Add-ons details
$module_description = "A complete event management suite - former known as kitEvent";
