<?php

/**
 * flexContent - phpManufaktur
 *
 * This file was generated by the kitFramework
 */
 
$module_directory     = 'kit_framework_flexcontent';
$module_name          = 'flexContent';
$module_function      = 'tool';
$module_version       = '0.45';
$module_platform      = '2.8.x';
$module_author        = 'phpManufaktur';
$module_license       = 'MIT License';
$module_description   = 'Manage different contents flexibel with the kitFramework';
$module_guid          = '{GUID}';
