<?php
// *** This file is generated by WebsiteBaker Ver.2.8.3
// *** Creation date: 2014-11-12T13:47:42+00:00
// *** Do not modify this file manually
// *** WB will rebuild this file from time to time!!
// *************************************************
	$page_id    = 30;
	require('../index.php');
// *************************************************
