<?php

/**
 * ConfirmationLog - phpManufaktur
 *
 * This file was generated by the kitFramework
 */
 
$module_directory     = 'kit_framework_confirmationlog';
$module_name          = 'ConfirmationLog';
$module_function      = 'tool';
$module_version       = '0.22';
$module_platform      = '2.8.x';
$module_author        = 'phpManufaktur';
$module_license       = 'MIT License';
$module_description   = 'User can confirm that they have viewed a page or read an article.';
$module_guid          = '{GUID}';
