<?php

/**
 * Event - phpManufaktur
 *
 * This file was generated by the kitFramework
 */
 
$module_directory     = 'kit_framework_event';
$module_name          = 'Event';
$module_function      = 'tool';
$module_version       = '2.0.21';
$module_platform      = '2.8.x';
$module_author        = 'phpManufaktur';
$module_license       = 'MIT License';
$module_description   = 'A complete event management suite - former known as kitEvent';
$module_guid          = '{GUID}';
