<?php
// *** This file is generated by WebsiteBaker Ver.2.8.3
// *** Creation date: 2013-11-07T05:56:29+00:00
// *** Do not modify this file manually
// *** WB will rebuild this file from time to time!!
// *************************************************
	header('HTTP/1.1 301 Moved Permanently');
	header('Location: ../index.php');
// *************************************************
