<?php

/**
 * miniShop - phpManufaktur
 *
 * This file was generated by the kitFramework
 */
 
$module_directory     = 'kit_framework_minishop';
$module_name          = 'miniShop';
$module_function      = 'tool';
$module_version       = '0.17';
$module_platform      = '2.8.x';
$module_author        = 'phpManufaktur';
$module_license       = 'MIT License';
$module_description   = 'Small and easy to use shop for your website';
$module_guid          = '{GUID}';
